# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7b80\u4ecb')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('last_modify', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=1000, verbose_name='\u4f18\u5148\u7ea7')),
                ('head_img', models.ImageField(upload_to=b'uploads', verbose_name='\u6587\u7ae0\u6807\u9898\u56fe\u7247')),
                ('status', models.CharField(choices=[(b'draft', '\u8349\u7a3f'), (b'published', '\u5df2\u53d1\u5e03'), (b'hidden', '\u9690\u85cf')], default=b'published', max_length=32, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u7248\u5757\u540d\u79f0')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7248\u5757\u7b80\u4ecb')),
                ('set_as_top_menu', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7f6e\u9876\u663e\u793a')),
                ('position_index', models.SmallIntegerField(verbose_name='\u5bfc\u822a\u680f\u6743\u91cd')),
            ],
            options={
                'verbose_name': '\u7248\u5757',
                'verbose_name_plural': '\u7248\u5757',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.IntegerField(choices=[(1, '\u8bc4\u8bba'), (2, '\u70b9\u8d5e')], default=1, verbose_name='\u8bc4\u8bba\u7c7b\u578b')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Article', verbose_name='\u6240\u5c5e\u6587\u7ae0')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_children', to='bbs.Comment', verbose_name='\u7236\u7ea7\u8bc4\u8bba')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u6635\u79f0')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7b7e\u540d')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to=b'uploads', verbose_name='\u5934\u50cf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile', verbose_name='\u53d1\u5e03\u8005'),
        ),
        migrations.AddField(
            model_name='category',
            name='admins',
            field=models.ManyToManyField(blank=True, to='bbs.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile', verbose_name='\u53d1\u5e03\u8005'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Category', verbose_name='\u7248\u5757'),
        ),
    ]
