# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('aitutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTestM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfield', markdownx.models.MarkdownxField()),
            ],
            options={
                'db_table': 'ai_article',
                'managed': False,
            },
        ),
    ]
