# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aitutorial', '0002_aitestm'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aitestm',
            table='ai_testM',
        ),
    ]
